language: cpp
compiler:
    - gcc
before_install:
    # disable rvm, use system Ruby
    - rvm reset
    - wget https://raw.githubusercontent.com/yast/yast-devtools/master/travis-tools/travis_setup.sh
    - sh ./travis_setup.sh -p "rake yast2-core yast2-devtools yast2-testsuite yast2-ruby-bindings yast2-pkg-bindings ruby2.1-dev libaugeas-dev pkg-config" -g "rspec:3.3.0 yast-rake gettext coveralls rubocop:0.41.2 cheetah abstract_method cfa"
script:
    - rake check:pot
    - rubocop
    - make -s -f Makefile.cvs
    - make -s
    - sudo make -s install
    # English messages, UTF-8, "C" locale for numeric formatting tests
    - LC_ALL= LANG=en_US.UTF-8 LC_NUMERIC=C make -s check
    # English messages, UTF-8, "C" locale for numeric formatting tests, enable test coverage report
    - LC_ALL= LANG=en_US.UTF-8 LC_NUMERIC=C COVERAGE=1 rake test:unit

